import { User, Product, Portfolio, Transaction, Memo, Admin, DashboardMetrics, AuditLog, KycSubmission } from '@/types';

// Reduced mock users for easier testing
export const mockUsers: User[] = [
  {
    id: '1',
    email: 'john.doe@example.com',
    firstName: 'John',
    lastName: 'Doe',
    phone: '+1234567890',
    accountType: 'individual',
    status: 'active',
    kycStatus: 'approved',
    createdAt: '2024-01-15T10:30:00Z',
    lastLogin: '2024-01-20T14:22:00Z',
    totalInvested: 50000,
    portfolioValue: 52500,
  },
  {
    id: '4',
    email: 'mike.wilson@example.com',
    firstName: 'Mike',
    lastName: 'Wilson',
    phone: '+1234567892',
    accountType: 'joint',
    status: 'active',
    kycStatus: 'approved',
    createdAt: '2024-01-12T08:45:00Z',
    lastLogin: '2024-01-20T16:30:00Z',
    totalInvested: 75000,
    portfolioValue: 78500,
    jointAccountHolder: {
      firstName: 'Sarah',
      lastName: 'Wilson',
      email: 'sarah.wilson@example.com',
    },
  },
];

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Growth Equity Fund',
    description: 'High-growth equity investments in emerging markets',
    category: 'Equity',
    minimumInvestment: 10000,
    currentValue: 2500000,
    totalInvested: 2400000,
    annualReturn: 12.5,
    riskLevel: 'high',
    status: 'active',
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    name: 'Stable Income Bond',
    description: 'Conservative bond portfolio for steady returns',
    category: 'Fixed Income',
    minimumInvestment: 5000,
    currentValue: 1800000,
    totalInvested: 1750000,
    annualReturn: 6.8,
    riskLevel: 'low',
    status: 'active',
    createdAt: '2024-01-01T00:00:00Z',
  },
];

export const mockPortfolios: Portfolio[] = [
  {
    id: '1',
    userId: '1',
    userName: 'John Doe',
    totalValue: 52500,
    totalInvested: 50000,
    returnAmount: 2500,
    returnPercentage: 5.0,
    holdings: [
      {
        productId: '1',
        productName: 'Growth Equity Fund',
        investedAmount: 30000,
        currentValue: 31500,
        returnPercentage: 5.0,
        shares: 100,
      },
      {
        productId: '2',
        productName: 'Stable Income Bond',
        investedAmount: 20000,
        currentValue: 21000,
        returnPercentage: 5.0,
        shares: 200,
      },
    ],
    createdAt: '2024-01-15T10:30:00Z',
  },
  {
    id: '2',
    userId: '4',
    userName: 'Mike Wilson',
    totalValue: 78500,
    totalInvested: 75000,
    returnAmount: 3500,
    returnPercentage: 4.67,
    holdings: [
      {
        productId: '1',
        productName: 'Growth Equity Fund',
        investedAmount: 40000,
        currentValue: 42000,
        returnPercentage: 5.0,
        shares: 150,
      },
      {
        productId: '2',
        productName: 'Stable Income Bond',
        investedAmount: 35000,
        currentValue: 36500,
        returnPercentage: 4.29,
        shares: 350,
      },
    ],
    createdAt: '2024-01-12T08:45:00Z',
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: '1',
    userId: '1',
    userName: 'John Doe',
    type: 'deposit',
    amount: 50000,
    status: 'completed',
    description: 'Initial deposit',
    createdAt: '2024-01-15T10:30:00Z',
    completedAt: '2024-01-15T10:35:00Z',
  },
  {
    id: '2',
    userId: '1',
    userName: 'John Doe',
    type: 'investment',
    amount: 30000,
    status: 'completed',
    description: 'Investment in Growth Equity Fund',
    createdAt: '2024-01-15T11:00:00Z',
    completedAt: '2024-01-15T11:05:00Z',
    productId: '1',
    productName: 'Growth Equity Fund',
  },
  {
    id: '3',
    userId: '4',
    userName: 'Mike Wilson',
    type: 'deposit',
    amount: 75000,
    status: 'completed',
    description: 'Initial deposit for joint account',
    createdAt: '2024-01-12T08:45:00Z',
    completedAt: '2024-01-12T08:50:00Z',
  },
];

export const mockMemos: Memo[] = [
  {
    id: '1',
    adminId: '1',
    adminName: 'Admin User',
    title: 'Market Update: Q1 2024 Performance',
    content: 'We are pleased to share our Q1 2024 market performance update. Our diversified portfolio has shown strong resilience despite market volatility. Key highlights include:\n\n• Growth Equity Fund: +12.5% YTD\n• Stable Income Bond: +6.8% YTD\n• Real Estate REIT: +8.2% YTD\n\nWe continue to monitor market conditions closely and adjust our strategies accordingly.',
    targetAudience: 'all',
    status: 'published',
    createdAt: '2024-01-19T10:30:00Z',
    publishedAt: '2024-01-19T14:00:00Z',
  },
  {
    id: '2',
    adminId: '1',
    adminName: 'Admin User',
    title: 'Understanding Risk Management for Individual Investors',
    content: 'As an individual investor, understanding risk management is crucial for long-term success. Here are key principles to consider:\n\n1. Diversification: Spread investments across different asset classes\n2. Risk Tolerance: Align investments with your comfort level\n3. Time Horizon: Consider your investment timeline\n4. Regular Review: Monitor and adjust your portfolio periodically\n\nOur team is always available to help you optimize your investment strategy.',
    targetAudience: 'individual',
    status: 'published',
    createdAt: '2024-01-18T09:15:00Z',
    publishedAt: '2024-01-18T12:00:00Z',
  },
  {
    id: '3',
    adminId: '1',
    adminName: 'Admin User',
    title: 'Joint Account Benefits and Tax Considerations',
    content: 'Joint investment accounts offer unique advantages for couples and partners:\n\n• Shared Decision Making: Both parties can manage investments\n• Survivorship Rights: Automatic transfer upon death\n• Tax Benefits: Potential for income splitting strategies\n• Estate Planning: Simplified wealth transfer\n\nConsider consulting with our financial advisors to maximize these benefits while understanding the tax implications.',
    targetAudience: 'joint',
    status: 'published',
    createdAt: '2024-01-17T14:20:00Z',
    publishedAt: '2024-01-17T16:00:00Z',
  },
];

export const mockAdmins: Admin[] = [
  {
    id: '1',
    email: 'admin@estiencapital.com',
    firstName: 'Admin',
    lastName: 'User',
    role: 'super_admin',
    permissions: ['all'],
    createdAt: '2024-01-01T00:00:00Z',
    lastLogin: '2024-01-20T08:00:00Z',
  },
  {
    id: '2',
    email: 'moderator@estiencapital.com',
    firstName: 'Moderator',
    lastName: 'User',
    role: 'moderator',
    permissions: ['view_users', 'moderate_memos'],
    createdAt: '2024-01-01T00:00:00Z',
    lastLogin: '2024-01-19T16:30:00Z',
  },
];

export const mockDashboardMetrics: DashboardMetrics = {
  totalUsers: 1248,
  activeUsers: 1156,
  individualAccounts: 892,
  jointAccounts: 356,
  pendingKyc: 23,
  totalAssets: 125000000,
  monthlyTransactionVolume: 8500000,
  totalTransactions: 5420,
  pendingTransactions: 18,
  totalProducts: 12,
  activeProducts: 9,
  publishedMemos: 15,
};

export const mockAuditLogs: AuditLog[] = [
  {
    id: '1',
    adminId: '1',
    adminName: 'Admin User',
    action: 'user_kyc_approved',
    entityType: 'user',
    entityId: '1',
    changes: { kycStatus: 'approved' },
    createdAt: '2024-01-20T10:30:00Z',
  },
  {
    id: '2',
    adminId: '1',
    adminName: 'Admin User',
    action: 'product_created',
    entityType: 'product',
    entityId: '3',
    changes: { name: 'Real Estate REIT', status: 'active' },
    createdAt: '2024-01-19T14:22:00Z',
  },
  {
    id: '3',
    adminId: '1',
    adminName: 'Admin User',
    action: 'memo_published',
    entityType: 'memo',
    entityId: '1',
    changes: { status: 'published', targetAudience: 'all' },
    createdAt: '2024-01-19T14:00:00Z',
  },
];

export const mockKycSubmissions: KycSubmission[] = [
  {
    id: '1',
    userId: '2',
    documentType: 'passport',
    documentUrl: '/documents/passport-jane-smith.pdf',
    status: 'pending',
    submittedAt: '2024-01-18T09:30:00Z',
  },
  {
    id: '2',
    userId: '1',
    documentType: 'driver_license',
    documentUrl: '/documents/license-john-doe.pdf',
    status: 'approved',
    submittedAt: '2024-01-15T11:00:00Z',
    reviewedAt: '2024-01-16T10:00:00Z',
    reviewedBy: 'Admin User',
    notes: 'All documents verified successfully',
  },
];